# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='expire_date',
            field=models.DateField(default='2001-12-21'),
        ),
        migrations.AddField(
            model_name='batch',
            name='manufacturing_date',
            field=models.DateField(default='2001-12-21'),
        ),
        migrations.AddField(
            model_name='batch',
            name='purchase_date',
            field=models.DateField(default='2001-12-21'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(default='x@y.com', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='x@y.com', max_length=254),
        ),
    ]
