# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('contact_no', models.IntegerField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('blood_group', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=1000)),
                ('appointment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.Appointment')),
                ('patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Patient')),
            ],
        ),
    ]
