# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_patient_contact_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthistory',
            old_name='appointment_ID',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='patienthistory',
            old_name='patient_ID',
            new_name='patient',
        ),
    ]
